### ISSUE TITLE
nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]

### ISSUE THREAD

**Issue by hero007asd** [elasticsearch/elasticsearch#9191]
I create the mappings and a snippet as following:
>"weight": {
    "type": "integer"
}

And ,when i search by 
>{
  "sort": [
    {
      "weight": {
        "order": "desc"
      }
    },
    "_score"
  ]
}

es server reports:
>nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]

I'm using es-1.4.2 on centOs.

**Comment by Hoannv** [comment]
I had same issue for yesterday

```
school:
                    mappings:
                        name: ~
                        shortName: ~
                        city: ~
                        address: ~
                        description: ~
                        rankingTotal: { type : integer }
```
Where I order by rankingTotal, it throws below error.
```
SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[l2T3o59-S5GXM3CRgQlomw][abcxyz][0]: QueryPhaseExecutionException[[abcxyz][0]: query[filtered(+((name:boston^4.0 | shortName:boston | city:boston^2.0 | address:boston | description:boston | area.title:boston | area.shortTitle:boston | area.parent.title:boston | area.parent.shortTitle:boston) ToParentBlockJoinQuery (filtered((topSchools.speciality.title:boston | topSchools.speciality.prefixTitle:boston | topSchools.speciality.suffixTitle:boston | topSchools.speciality.shortTitle:boston | topSchools.speciality.shortDescription:boston))->cache(_type:__topSchools)) ToParentBlockJoinQuery (filtered(profiles.content:boston)->cache(_type:__profiles))))->cache(_type:school)],from[0],size[10],sort[,,]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }]
```
But it's working fine when I remove order by rankingtotal
