### ISSUE TITLE
Testing: RestClient does not escape `source` HTTP parameter correctly

### ISSUE THREAD

**Issue by spinscale** [elasticsearch/elasticsearch#9769]
This test reproduces the issue. Be aware, that this only happens, when the whole source is put into the `source` HTTP parameter and not sent as body, You can control this behaviour in `RestClient.callApiBuilder()` for testing purposes

```yaml
---
"Expressions scripting test":

  - do:
      index:
        index:  test123
        type:   test
        id:     1
        body:   { age: 23 }

  - do:
      indices.refresh: {}

  - do: { search: { body: { script_fields : { my_field : { lang: expression, script: 'doc["age"].value + 19' } } } } }
  - match:  { hits.hits.0.fields.my_field: [ 42.0 ] }
```

The problem is, that everything gets encoded correctly, with the exception of the `+` sign, which gets replaced with a space upon decoding - and this makes the script compilation fail.
